#
# Copyright 2004 Peter Chen <peterc@socle-tech.com.tw>
#
# SPDX-License-Identifier:	GPL-2.0+

# include $(TOPDIR)/config.mk

obj-y	= io.o
obj-y	+= timer.o
obj-y	+= reset.o
obj-y	+= mactest.o
obj-y	+= dram_spi.o
obj-y	+= lib.o
obj-y	+= mac.o
obj-y	+= ncsi.o
obj-y	+= pci_spi.o
obj-y	+= phy.o
obj-y	+= spim.o
obj-y	+= stduboot.o
obj-y	+= plltestu.o
obj-y	+= traptest.o
obj-y	+= stress.o
