# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307 USA
#

obj-y := ast2400.o
obj-y += flash.o
obj-y += flash_spi.o
obj-y += pci.o
obj-y += crc32.o
obj-y += slt.o 
obj-y += regtest.o
obj-y += vfun.o
obj-y += vhace.o
obj-y += crt.o
obj-y += videotest.o
obj-y += mactest.o
obj-y += hactest.o
obj-y += mictest.o
obj-y += platform.o
